### ISSUE TITLE
Chroot error

### ISSUE THREAD

**Issue by dado3272** [ParrotSec/parrot-iso-build#11]
Hello, I get this problem every time I try to build a parrot version with this script.

[2017-12-24 17:54:00] lb build noauto
P: live-build 1:20171207kali1
P: Building config tree for a debian/parrot/amd64 system
[2017-12-24 17:54:01] lb bootstrap 
P: Setting up cleanup function
[2017-12-24 17:54:01] lb bootstrap_cache restore
P: Restoring bootstrap stage from cache...
[2017-12-24 17:54:01] lb bootstrap_debootstrap 
P: Begin bootstrapping system...
P: If the following stage fails, the most likely cause of the problem is with your mirror configuration or a caching proxy.
P: Running debootstrap (download-only)... 
I: Retrieving InRelease 
I: Checking Release signature
E: Release signed by unknown key (key id ED05F7B2EC3C9224)
P: Begin unmounting filesystems...
P: Saving caches...
chroot: failed to run command ‘/usr/bin/env’: No such file or directory

**Comment by PalinuroSec** [comment]
hi, i need more information on what you did

anyways the problem is caused by the absence of the parrot GPG key in the apt keyring used by the bootstrap

**Comment by PalinuroSec** [comment]
it looks like you don't have the parrot archive keyring available in your host system

**Comment by Gmm09x** [comment]
try updating the keyring with sudo apt-key adv --refresh-keys and reinstalling the coreutils package with sudo apt-get install --reinstall coreutils.
